spring.application.name=dream-journal-api

google.cloud.project-id=${GOOGLE_CLOUD_PROJECT_ID:project-f148f1df-8994-412a-868}
google.cloud.database-id=${GOOGLE_CLOUD_DATABASE_ID:(default)}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:8081,http://localhost:3000}
server.port=8081
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
springdoc.swagger-ui.enabled=${SWAGGER_UI_ENABLED:true}
logging.level.root=INFO

