spring.application.name=dream-journal-api
google.cloud.project-id=project-f148f1df-8994-412a-868
app.cors.allowed-origins=http://localhost:8081,http://localhost:3000

# Optional local emulator:
#FIRESTORE_EMULATOR_HOST=localhost:8080
