package com.example.dreamjournal.service;

import net.sf.jsqlparser.parser.CCJSqlParserUtil;
import net.sf.jsqlparser.statement.Statement;
import net.sf.jsqlparser.statement.select.Select;
import net.sf.jsqlparser.util.TablesNamesFinder;
import org.springframework.stereotype.Service;

import java.util.Locale;
import java.util.Set;

@Service
public class AnalyticsSqlValidator {

    private static final String PROJECT =
            "project-f148f1df-8994-412a-868";

    private static final String DATASET =
            "dream_atlas_health";

    private static final Set<String> ALLOWED_TABLES = Set.of(
            PROJECT + "." + DATASET + ".dreams_analytical",
            PROJECT + "." + DATASET + ".daily_dream_sleep",
            PROJECT + "." + DATASET + ".sleep_session_metrics",
            PROJECT + "." + DATASET + ".dreams_for_ai"
    );

    public void validate(String sql) {

        if (sql == null || sql.isBlank()) {
            throw new IllegalArgumentException(
                    "Gemini returned empty SQL"
            );
        }

        String cleanedSql = sql.trim();

        /*
         * Reject multiple SQL statements.
         *
         * A single trailing semicolon is allowed.
         */
        String sqlWithoutTrailingSemicolon =
                cleanedSql.endsWith(";")
                        ? cleanedSql.substring(
                        0,
                        cleanedSql.length() - 1
                ).trim()
                        : cleanedSql;

        if (sqlWithoutTrailingSemicolon.contains(";")) {
            throw new IllegalArgumentException(
                    "Multiple SQL statements are not allowed"
            );
        }


        try {

            /*
             * Parse the SQL into an AST.
             *
             * We intentionally don't use withDialect() here.
             * The normal parser already handles the BigQuery SQL
             * Gemini is currently generating.
             */
            Statement statement =
                    CCJSqlParserUtil.parse(cleanedSql);

            /*
             * Only SELECT statements are allowed.
             */
            if (!(statement instanceof Select)) {
                throw new IllegalArgumentException(
                        "Only SELECT queries are allowed"
                );
            }

            /*
             * Find every table referenced by the parsed query.
             *
             * This also walks nested queries.
             */
            Set<String> referencedTables =
                    TablesNamesFinder.findTables(statement.toString());

            if (referencedTables.isEmpty()) {
                throw new IllegalArgumentException(
                        "Query does not reference an approved data source"
                );
            }

            /*
             * Every referenced table must be one of our
             * four approved analytical sources.
             */
            for (String table : referencedTables) {

                String normalizedTable =
                        normalizeTableName(table);

                if (!ALLOWED_TABLES.contains(normalizedTable)) {
                    throw new IllegalArgumentException(
                            "Query references unauthorized table: "
                                    + table
                    );
                }
            }

            /*
             * Identity-based access is never allowed.
             *
             * User isolation is enforced by the backend using
             * the Firebase UID.
             */
            String normalizedSql =
                    cleanedSql.toLowerCase(Locale.ROOT);

            if (normalizedSql.contains("session_user")
                    || normalizedSql.contains("current_user")) {

                throw new IllegalArgumentException(
                        "Identity functions are not allowed"
                );
            }

            /*
             * Never allow BigQuery system metadata.
             */
            if (normalizedSql.contains("information_schema")) {
                throw new IllegalArgumentException(
                        "System metadata is not allowed"
                );
            }

        } catch (IllegalArgumentException e) {

            throw e;

        } catch (Exception e) {

            throw new IllegalArgumentException(
                    "Invalid or unsupported SQL generated by Gemini",
                    e
            );
        }
    }

    private String normalizeTableName(String table) {

        return table
                .replace("`", "")
                .replace("\"", "")
                .trim()
                .toLowerCase(Locale.ROOT);
    }
}